server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/registration
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
    show-sql: true
    generate-ddl: true
